### ISSUE TITLE
Catchable Fatal Error: Argument 4 passed to PimEnterprise\Bundle\ClassificationRuleBundle\Engine\ProductRuleApplier\ProductsUpdater::__construct() must be an instance of Pim\Bundle\CatalogBundle\Repository\CategoryRepositoryInterface  

### ISSUE THREAD

**Issue by manh-nguyen** [akeneo-labs/ClassificationRuleBundle#10]
Hi guys, 

I got this error when running the rule on Akeneo 1.4
{code}
Catchable Fatal Error: Argument 4 passed to PimEnterprise\Bundle\ClassificationRuleBundle\Engine\ProductRuleApplier\ProductsUpdater::__construct() must be an instance of Pim\Bundle\CatalogBundle\Repository\CategoryRepositoryInterface  
  , instance of Akeneo\Bundle\ClassificationBundle\Doctrine\ORM\Repository\CategoryRepository given
{code}

We used this bundle ClassificationRuleBundle. I checked the detail of probblem and known: 
In file vendor/akeneo-labs/classification-rule-bundle/PimEnterprise/Bundle/ClassificationRuleBundle/Engine/ProductRuleApplier/ProductsUpdater.php

The constructor has the old namespace type for parameter
Pim\Bundle\CatalogBundle\Repository\CategoryRepositoryInterface
It should be replaced by
Akeneo\Component\Classification\Repository\CategoryRepositoryInterface

I think you guys should update this bundle to make it support Akeneo 1.4.

Please check and give me notification when it's fixed.

Regards,
Manh - Balance Internet

**Comment by damien-carcel** [comment]
Hello Manh.

We just released version 1.0.0, which support Akeneo 1.4.
Update your Akeneo installation by using "akeneo-labs/classification-rule-bundle": "1.0.*" in your project composer.json file, and run "php composer.phar akeneo-labs/classification-rule-bundle update".

Regards,
Damien
